---
- name: Restart nfs-server.service
  become: true
  ansible.builtin.systemd_service:
    name: nfs-server.service
    state: restarted
    enabled: true
    daemon_reload: true
  delegate_to: localhost

- name: Update exportfs
  become: true
  ansible.builtin.command:
    cmd: exportfs -a
  delegate_to: localhost

- name: Restart mpi.automount
  become: true
  ansible.builtin.systemd_service:
    name: mpi.automount
    state: restarted
    enabled: true
    daemon-reload: true
