---
- name: Restart nfs-server service on localhost
  ansible.builtin.systemd:
    name: nfs-server.service
    daemon_reload: true
    state: restarted
    enabled: true
  delegate_to: localhost

- name: Reboot
  ansible.builtin.reboot
  listen: reconnect

- name: Waiting connection
  ansible.builtin.wait_for_connection:
  delay: 5
  timeout: 60
  listen: reconnect
