---
- name: Del apptainer symbolic link
  become: true
  ansible.builtin.file:
    path: "{{ apptainer.link_dir }}/{{ apptainer.command }}"
    state: absent

- name: Del apptainer folder
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/{{ apptainer.install_dir }}"
    state: absent

- name: Run apptainer installer
  ansible.builtin.command:
    argv:
      - /bin/bash
      - "{{ apptainer.installer.script }}"
      - "{{ apptainer.install_dir }}"
    chdir: "{{ ansible_facts.env.HOME }}"

- name: Create apptainer symbolic link
  become: true
  ansible.builtin.file:
    src: "/home/{{ mpi.user }}/{{ apptainer.install_dir }}/bin/{{ apptainer.command }}"
    dest: "{{ apptainer.link_dir }}/{{ apptainer.command }}"
    state: link
