---
sharedfolder:
  path: "/mpi"
  group: "mpi"
  owner: "mpi"
  mode: "0777"

nfs:
  opt: "(rw,sync,no_subtree_check)"

packages:
  controller:
    - nfs-kernel-server
    - nfs-common
  target:
    - nfs-common
