---
packages:
  control:
    - nfs-kernel-server
  compute:
    - nfs-common

exports:
  ipaddress: "192.168.68.0/24"
  options: "(rw,sync,no_subtree_check)"

mpi_mount:
  - { sec: Unit, opt: Description, val: "mount mpi" }
  - { sec: Mount, opt: What, val: "{{ mpi.control_node }}:{{ mpi.path }}" }
  - { sec: Mount, opt: Where, val: "{{ mpi.path }}" }
  - { sec: Mount, opt: Type, val: "nfs" }

mpi_automount:
  - { sec: Unit, opt: Description, val: "automount mpi" }
  - { sec: Automount, opt: Where, val: "{{ mpi.path }}" }
  - { sec: Install, opt: WantedBy, val: "multi-user.target" }
