---
- name: Restart munge.service
  ansible.builtin.systemd_service:
    name: munge.service
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart slurmctld.service
  ansible.builtin.systemd_service:
    name: slurmctld.service
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart slurmd.service
  ansible.builtin.systemd_service:
    name: slurmd.service
    state: restarted
    enabled: true
    daemon_reload: true