---
- name: Restart munge.service
  become: true
  ansible.builtin.systemd_service:
    name: munge.service
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart slurmctld.service
  become: true
  ansible.builtin.systemd_service:
    name: slurmctld.service
    state: restarted
    enabled: true
    daemon_reload: true
  delegate_to: localhost

- name: Restart slurmd.service
  become: true
  ansible.builtin.systemd_service:
    name: slurmd.service
    state: restarted
    enabled: true
    daemon_reload: true
