---
- name: Install slurm packages on compute node
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.compute }}"
  notify: Restart slurmd.service

- name: Chown mpi.user /var
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mpi.user }}"
    group: "{{ mpi.user }}"
  loop: "{{ var_folders }}"
  notify: Restart slurmd.service

- name: Update slurmd.service
  become: true
  community.general.ini_file:
    path: /lib/systemd/system/slurmd.service
    section: "{{ item.sect }}"
    option: "{{ item.opt }}"
    values: "{{ item.vals }}"
    state: "{{ item.stat }}"
    backup: true
    no_extra_spaces: true
  loop: "{{ slurmd_service }}"
  notify: Restart slurmd.service

- name: flush handlers
  ansible.builtin.meta: flush_handlers
