---
- name: Update control node
  block:
    - name: Install slurm packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages.control }}"

    - name: Create conf files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: false
      loop: "{{ conf_files }}"

    - name: Update slurm.conf
      ansible.builtin.lineinfile:
        path: /etc/slurm/slurm.conf
        regexp: "^#{{ item.item }}|^{{ item.item }}"
        line: "{{ item.item }}={{ item.value }}"
        firstmatch: true
      loop: "{{ slurm_conf }}"

    - name: Update cgroup.conf
      ansible.builtin.lineinfile:
        path: /etc/slurm/cgroup.conf
        regexp: "^#{{ item.item }}|^{{ item.item }}"
        line: "{{ item.item }}={{ item.value }}"
        firstmatch: true
      loop: "{{ cgroup_conf }}"

  delegate_to: localhost
  run_once: true
  notify:
    - Restart slurmctld.servide
    - Restart slurmd.service

- name: Install slurm packages on compute node
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.compute }}"
  notify: Restart Slurmd.service

- name: Chown slurm-var-folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: mpi
    group: mpi
  loop: "{{ var_folders }}"
  notify: Restart slurmd.service

#- name: Update slurmd.service
#  ansible.builtin.lineinfile:
#    path: /lib/systemd/system/slurmd.service
#    regexp: "^{{ item.src }}"
#    line: "{{ item.dest }}"
#  loop: "{{ slurmd_service }}"
#  notify: Restart slurmd.service