---
- name: Update control node
  block:
    - name: Install nfs-server packages
      ansible.builtin.package:
        state: latest
        name: "{{ item }}"
      loop: "{{ packages.control }}"

    - name: Create shared folder
      ansible.builtin.file:
        state: directory
        path: "{{ sharedfolder.path }}"
        mode: "{{ sharedfolder.mode }}"
        owner: "{{ sharedfolder.owner }}"
        group: "{{ sharedfolder.group }}"

    - name: Update exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        regexp: "^{{ sharedfolder.path }}"
        line: "{{ sharedfolder.path }} {{ exports.ipaddress }}{{ exports.options }}"
        backup: true
      notify: Update exportfs

  delegate_to: localhost
  run_once: true
  notify: Restart mfs-server.service

- name: flush handlers
  ansible.builtin.meta: flush_handlers