---
- name: Update control node
  become: true
  block:
    - name: Install nfs-server packages
      ansible.builtin.package:
        state: latest
        name: "{{ item }}"
      loop: "{{ packages.control }}"

    - name: Create shared folder
      ansible.builtin.file:
        state: directory
        path: "{{ mpi.path }}"
        mode: "0777"
        owner: "{{ mpi.user }}"
        group: "{{ mpi.user }}"

    - name: Update exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        regexp: "^{{ mpi.path }}"
        line: "{{ mpi.path }} {{ exports.ipaddress }}{{ exports.options }}"
        backup: true
      notify: Update exportfs

  delegate_to: localhost
  run_once: true
  notify: Restart mfs-server.service

- name: flush handlers
  ansible.builtin.meta: flush_handlers
