---
- name: Restart dnsmasq.service
  become: true
  ansible.builtin.systemd_service:
    name: dnsmasq.service
    state: restarted
    enabled: true
    daemon-reload: true
  delegate_to: localhost

- name: Activate nmcli wired
  become: true
  ansible.builtin.reboot:
