---
- name: Restart dnsmasq.service
  ansible.builtin.systemd_service:
    name: dnsmasq.service
    state: restarted
    enabled: true
    daemon-reload: true

- name: Activate nmcli wired
  ansible.builtin.reboot:
#  ansible.builtin.command: nmcli con up "wired"