---
packages:
  control:
    - slurm-wlm
  compute:
    - slurmd

var_folders:
  - "/var/lib/slurm"
  - "/var/log/slurm"

conf_files:
  - { src: "slurm.conf.default", dest: "/etc/slurm/slurm.conf" }
  - { src: "cgroup.conf.default", dest: "/etc/slurm/cgroup.conf" }

slurm_conf:
  - { opt: SlurmctldHost, vals: ["{{ mpi.control_node }}"] }
  - { opt: NodeName, vals: ["{{ slurm.nodename }}"] }
  - { opt: SlurmUser, vals: ["{{ mpi.user }}"] }
  - { opt: MpiDefault, vals: ["pmix"] }
  - { opt: TaskPlugin, vals: ["task/cgroup,task/affinity"] }
  - { opt: ProctrackType, vals: ["proctrack/cgroup"] }
  - { opt: JobAcctGatherType, vals: ["jobacct_gather/cgroup"] }
  - { opt: PrologFlags, vals: ["Contain"] }
  - { opt: SlurmctldParameters, vals: ["enable_configless"] }

cgroup_conf:
  - { opt: CgroupPlugin, vals: ["autodetect"] }
  - { opt: ConstrainCores, vals: ["yes"] }
  - { opt: ConstrainDevices, vals: ["yes"] }
  - { opt: ConstrainRAMSpace, vals: ["no"] }
  - { opt: ConstrainSwapSpace, vals: ["no"] }

slurmd_service:
  - { sect: Unit, opt: ConditionPathExists, vals: [], stat: absent }
  - { sect: Service, opt: ExecStart, vals: ["/usr/sbin/slurmd --conf-server {{ mpi.control_node }} -D -s $SLURMD_OPTIONS"], stat: present }
